apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-test-project
  labels:
    app: pipeline-test-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pipeline-test-project
  template:
    metadata:
      labels:
        app: pipeline-test-project
    spec:
      containers:
      - name: pipeline-test-project
        image: aswingopakumar04/pipeline-test-project:${BUILD_TAG}
        ports:
        - containerPort: 3000
