apiVersion: v1
kind: Service
metadata:
  name: pipeline-test-project-service
spec:
  type: NodePort
  selector:
    app: pipeline-test-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007  # You can pick any port between 30000–32767
